# Generated by Django 5.0.3 on 2024-10-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_services_requirements'),
        ('profiles', '0004_user_function_invocations_and_more'),
        ('providers', '0002_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delay',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='developer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_developer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_developer', to='profiles.user'),
        ),
        migrations.AddField(
            model_name='job',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developers.services'),
        ),
        migrations.AddField(
            model_name='job',
            name='time_of_last_startjob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'is_provider': True}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_provider', to='profiles.user'),
        ),
    ]
