# Generated by Django 5.0.3 on 2024-11-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_job_delay_job_developer_job_reputation_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='reputation_score',
        ),
        migrations.RemoveField(
            model_name='job',
            name='time_of_last_startjob',
        ),
    ]
