# Generated by Django 5.0.3 on 2025-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_remove_job_delay_remove_job_reputation_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ack_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
