# Generated by Django 5.0.3 on 2025-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_alter_job_ack_time_alter_job_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_recovery_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='recovery_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent to Provider'), ('ACKNOWLEDGED', 'Acknowledged by Provider'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
    ]
