# Generated by Django 5.0.3 on 2025-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_job_last_recovery_attempt_job_recovery_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_recovery_attempt',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recovery_attempts',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
