# Generated by Django 5.0.3 on 2026-04-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_add_request_timing_fields'),
    ]

    operations = [
        # DB may never have had 0006 columns (e.g. faked migrations / restored schema).
        # Plain RemoveField fails with "column does not exist"; use IF EXISTS on Postgres/CRDB.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE providers_job DROP COLUMN IF EXISTS last_recovery_attempt;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    'ALTER TABLE providers_job DROP COLUMN IF EXISTS recovery_attempts;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    'ALTER TABLE providers_job DROP COLUMN IF EXISTS status;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='job',
                    name='last_recovery_attempt',
                ),
                migrations.RemoveField(
                    model_name='job',
                    name='recovery_attempts',
                ),
                migrations.RemoveField(
                    model_name='job',
                    name='status',
                ),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='cpu_efficiency_score',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cpu_usage',
            field=models.BigIntegerField(blank=True, help_text='Container CPU usage (total_usage)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='memory_efficiency_score',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='memory_usage',
            field=models.BigIntegerField(blank=True, help_text='Container memory usage in bytes', null=True),
        ),
    ]
