# Generated by Django 6.0.4 on 2026-07-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_job_predicted_runtime_ms_job_prediction_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cache_state',
            field=models.CharField(blank=True, help_text="Image cache state at execution time reported by provider: 'memory', 'disk', or 'cold'", max_length=8, null=True),
        ),
    ]
