# Generated by Django 5.0.3 on 2024-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
