# Generated by Django 5.0.3 on 2024-11-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_services_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='provider',
        ),
    ]
