# Generated by Django 5.0.3 on 2024-11-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_remove_services_provider'),
        ('profiles', '0004_user_function_invocations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='provider',
            field=models.ManyToManyField(limit_choices_to={'is_provider': True}, related_name='services_handled', to='profiles.user'),
        ),
    ]
