# Generated by Django 5.0.3 on 2024-11-15 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_services_provider'),
        ('profiles', '0005_user_delay_user_reputation_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='provider',
        ),
        migrations.AddField(
            model_name='services',
            name='provider',
            field=models.ForeignKey(default=16, limit_choices_to={'is_provider': True}, on_delete=django.db.models.deletion.CASCADE, related_name='services_as_provider', to='profiles.user'),
            preserve_default=False,
        ),
    ]
