# Generated by Django 5.0.3 on 2025-02-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_remove_services_provider_services_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='provider',
        ),
    ]
