# Generated by Django 5.0.3 on 2026-04-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0006_remove_services_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='reference_stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
