# Generated by Django 6.0.4 on 2026-07-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0008_services_cpu_cycles_memory_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_size_mb',
            field=models.FloatField(blank=True, help_text='Docker image size in MB (drives pull-time estimate)', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='ref_runtime_ms',
            field=models.IntegerField(blank=True, help_text='Median runtime on BEM reference machine (ms)', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='w_cpu',
            field=models.FloatField(blank=True, help_text='CPU weight for scaling formula', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='w_disk',
            field=models.FloatField(blank=True, help_text='Disk I/O weight for scaling formula', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='w_mem',
            field=models.FloatField(blank=True, help_text='Memory weight for scaling formula', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='w_net',
            field=models.FloatField(blank=True, help_text='Network weight for scaling formula', null=True),
        ),
    ]
