[managed]
cortalim1.dashlab.in ansible_user=cortalim1 ansible_become_pass=raspberry
cortalim2.dashlab.in ansible_user=cortalim2 ansible_become_pass=raspberry
cortalim3.dashlab.in ansible_user=cortalim3 ansible_become_pass=raspberry
cortalim4.dashlab.in ansible_user=cortalim4 ansible_become_pass=raspberry
cortalim5.dashlab.in ansible_user=cortalim5 ansible_become_pass=raspberry
cortalim6.dashlab.in ansible_user=cortalim6 ansible_become_pass=raspberry
cortalim7.dashlab.in ansible_user=cortalim7 ansible_become_pass=raspberry
cortalim8.dashlab.in ansible_user=cortalim8 ansible_become_pass=raspberry
cortalim9.dashlab.in ansible_user=cortalim9 ansible_become_pass=raspberry
cortalim10.dashlab.in ansible_user=cortalim10 ansible_become_pass=raspberry
cortalim11.dashlab.in ansible_user=cortalim11 ansible_become_pass=raspberry
cortalim12.dashlab.in ansible_user=cortalim12 ansible_become_pass=raspberry
cortalim13.dashlab.in ansible_user=cortalim13 ansible_become_pass=raspberry
cortalim14.dashlab.in ansible_user=cortalim14 ansible_become_pass=raspberry
cortalim15.dashlab.in ansible_user=cortalim15 ansible_become_pass=raspberry
cortalim16.dashlab.in ansible_user=cortalim16 ansible_become_pass=raspberry
cortalim17.dashlab.in ansible_user=cortalim17 ansible_become_pass=raspberry
cortalim18.dashlab.in ansible_user=cortalim18 ansible_become_pass=raspberry
# all cortalims have debian trixie excluding cortalim1/3/7 which have bookworm (12.6)

palolem1.dashlab.in ansible_user=palolem1 ansible_become_pass=nvidia
palolem2.dashlab.in ansible_user=palolem2 ansible_become_pass=nvidia
palolem3.dashlab.in ansible_user=palolem3 ansible_become_pass=nvidia
palolem4.dashlab.in ansible_user=palolem4 ansible_become_pass=nvidia
# all palolems (jetson nanos) have ubuntu jammy

[control]
utorda1.dashlab.in ansible_user=peercompute ansible_become_pass=peercompute
utorda2.dashlab.in ansible_user=peercompute ansible_become_pass=peercompute
colva3.dashlab.in ansible_user=peercompute ansible_become_pass=peercompute

[control:vars]

[managed:vars]
# ansible_python_interpreter=/usr/bin/python3 this is default anyways.

[palolems]
palolem1.dashlab.in ansible_user=palolem1 ansible_become_pass=nvidia
palolem2.dashlab.in ansible_user=palolem2 ansible_become_pass=nvidia
palolem3.dashlab.in ansible_user=palolem3 ansible_become_pass=nvidia
palolem4.dashlab.in ansible_user=palolem4 ansible_become_pass=nvidia

[cortalims]
cortalim1.dashlab.in ansible_user=cortalim1 ansible_become_pass=raspberry
cortalim2.dashlab.in ansible_user=cortalim2 ansible_become_pass=raspberry
cortalim3.dashlab.in ansible_user=cortalim3 ansible_become_pass=raspberry
cortalim4.dashlab.in ansible_user=cortalim4 ansible_become_pass=raspberry
cortalim5.dashlab.in ansible_user=cortalim5 ansible_become_pass=raspberry
cortalim6.dashlab.in ansible_user=cortalim6 ansible_become_pass=raspberry
cortalim7.dashlab.in ansible_user=cortalim7 ansible_become_pass=raspberry
cortalim8.dashlab.in ansible_user=cortalim8 ansible_become_pass=raspberry
cortalim9.dashlab.in ansible_user=cortalim9 ansible_become_pass=raspberry
cortalim10.dashlab.in ansible_user=cortalim10 ansible_become_pass=raspberry
cortalim11.dashlab.in ansible_user=cortalim11 ansible_become_pass=raspberry
cortalim12.dashlab.in ansible_user=cortalim12 ansible_become_pass=raspberry
cortalim13.dashlab.in ansible_user=cortalim13 ansible_become_pass=raspberry
cortalim14.dashlab.in ansible_user=cortalim14 ansible_become_pass=raspberry
cortalim15.dashlab.in ansible_user=cortalim15 ansible_become_pass=raspberry
cortalim16.dashlab.in ansible_user=cortalim16 ansible_become_pass=raspberry
cortalim17.dashlab.in ansible_user=cortalim17 ansible_become_pass=raspberry
cortalim18.dashlab.in ansible_user=cortalim18 ansible_become_pass=raspberry
