"""
Django settings for scheduler project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import datetime
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xgo+%_s-0piu0d7c$hhw$n6t5%ozqct71qrc(e8d!5flo@6n@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'profiles',
    'providers',
    'developers',
    'fabric',
    'experiments',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'scheduler.urls'

USE_FABRIC = False
CONTROLLER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTM5NzE5NTMsInVzZXJuYW1lIjoidGVtcCIsIm9yZ05hbWUiOiJPcmcxIiwiaWF0IjoxNjkzOTM1OTUzfQ.x06zMn-c0_e7_phfc3thS30R1H284V8x6xMda6rl6Ak"

CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scheduler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME':'peercompute',
#         'USER':'postgres',
#         'PASSWORD':'dash$123',
#         'HOST':'database-uno.c5gy8c44i5qo.us-east-2.rds.amazonaws.com',
#         'PORT':'5432',
#     }
# }

# # Local db 
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "peercompute_local_sn34kyp3t3",
#         "USER": "postgres",
#         "PASSWORD": "user123",
#         "HOST": "localhost",
#         "PORT": "5432",
#     }
# }


# SUPABASE
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres.uufnsxmqnwegackubear",
        "PASSWORD": "16G6MNonNa7ny9pG",
        "HOST": "aws-0-ap-south-1.pooler.supabase.com",
        "PORT": "5432",
        "OPTIONS": {
            "options": "-c pool_mode=session"
        },
    }
}

# # COCKROACHDB
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "defaultdb",
#         "USER": "root",
#         "PASSWORD": "",  # No password for insecure mode
#         "HOST": "localhost",
#         "PORT": "26257",
#         "OPTIONS": {
#             "sslmode": "disable",  # Required for insecure mode
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Scheduling Algorithm Configuration
SCHEDULING_ALGORITHM = 'ILP'  # Options: 'ILP', 'MRU', 'BELADY', 'ROUND_ROBIN'

#NOTE - Config for Experiment 5.

# Experiment Configuration
EXPERIMENT_MODE = True  # Set to True to enable experiment data collection
EXPERIMENT_LOG_FILE = '/home/user/Documents/Serverless_Scheduler_sn34kyp3t3/experiment_results.csv'
ALGORITHM_METRICS_FILE = '/home/user/Documents/Serverless_Scheduler_sn34kyp3t3/algorithm_metrics.csv'

# Stdout logging configuration for experiment mode
EXPERIMENT_STDOUT_LOGGING = True  # Enable stdout logging when EXPERIMENT_MODE is True
EXPERIMENT_LOGS_BASE_DIR = '/home/user/Documents/Serverless_Scheduler_sn34kyp3t3/experiment_logs'

# Dynamic log directory - can be overridden by environment variables
def get_experiment_logs_dir():
    """Get the current experiment logs directory"""
    # Check if algorithm-specific directory is set via environment
    experiment_algorithm = os.environ.get('EXPERIMENT_ALGORITHM')
    experiment_log_dir = os.environ.get('EXPERIMENT_LOG_DIR')
    
    if experiment_log_dir:
        return experiment_log_dir
    elif experiment_algorithm:
        # Create algorithm-specific directory
        timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        return os.path.join(EXPERIMENT_LOGS_BASE_DIR, timestamp, experiment_algorithm)
    else:
        # Default behavior
        timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        return os.path.join(EXPERIMENT_LOGS_BASE_DIR, timestamp)

# Add the method to the settings module
this_module = sys.modules[__name__]
setattr(this_module, 'get_experiment_logs_dir', get_experiment_logs_dir)

# Initialize log directory and files - but only if experiment mode is enabled
try:
    if EXPERIMENT_MODE and EXPERIMENT_STDOUT_LOGGING:
        EXPERIMENT_LOGS_DIR = get_experiment_logs_dir()
        SCHEDULER_LOG_FILE = os.path.join(EXPERIMENT_LOGS_DIR, 'scheduler_stdout.log')
        LOADBALANCER_LOG_FILE = os.path.join(EXPERIMENT_LOGS_DIR, 'loadbalancer_stdout.log')
        PROVIDER_LOG_FILE = os.path.join(EXPERIMENT_LOGS_DIR, 'provider_stdout.log')
    else:
        # Set default values when experiment mode is disabled
        EXPERIMENT_LOGS_DIR = None
        SCHEDULER_LOG_FILE = None
        LOADBALANCER_LOG_FILE = None
        PROVIDER_LOG_FILE = None
except Exception as e:
    print(f"Warning: Could not initialize experiment logging: {e}")
    EXPERIMENT_LOGS_DIR = None
    SCHEDULER_LOG_FILE = None
    LOADBALANCER_LOG_FILE = None
    PROVIDER_LOG_FILE = None

# Algorithm-specific settings
ROUND_ROBIN_STATE_FILE = '/home/user/Documents/Serverless_Scheduler_sn34kyp3t3/round_robin_state.json'
MRU_HISTORY_SIZE = 100  # Number of recent assignments to keep in memory
BELADY_PREDICTION_WINDOW = 50  # Number of future requests to consider (for simulation)

# For current machine
HOST = os.environ.get('HOST')
ENDPOINT = os.environ.get('ENDPOINT')

# Scheduler URLs Configuration
def get_scheduler_endpoints():
    """
    Get the list of scheduler URLs for load balancing.
    
    Returns:
        List[str]: List of scheduler endpoint URLs
    """
    # Default scheduler URLs - can be overridden by environment variables
    default_urls = [
        "http://localhost:8000",
        "http://localhost:8001",
        "http://localhost:8002"
    ]
    
    # Check if custom URLs are provided via environment variable
    custom_urls = os.environ.get('SCHEDULER_URLS')
    if custom_urls:
        try:
            import json
            return json.loads(custom_urls)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"Warning: Invalid SCHEDULER_URLS environment variable: {e}")
            print("Using default scheduler URLs")
    
    return default_urls
