"""
Django settings for scheduler project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xgo+%_s-0piu0d7c$hhw$n6t5%ozqct71qrc(e8d!5flo@6n@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'profiles',
    'providers',
    'developers',
    'fabric',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'scheduler.urls'

USE_FABRIC = False
CONTROLLER_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTM5NzE5NTMsInVzZXJuYW1lIjoidGVtcCIsIm9yZ05hbWUiOiJPcmcxIiwiaWF0IjoxNjkzOTM1OTUzfQ.x06zMn-c0_e7_phfc3thS30R1H284V8x6xMda6rl6Ak"

# Name of the strategy resolved by ``providers.prediction.registry.get_strategy``.
# See ``providers/prediction/__init__.py`` for the plug-and-play contract.
RUNTIME_PREDICTION_STRATEGY = os.environ.get("RUNTIME_PREDICTION_STRATEGY", "cpi")

CORS_ORIGIN_ALLOW_ALL = True

# Host configuration for provider connections
HOST = "localhost"  # Change this to your machine's IP address for remote connections

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scheduler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME':'peercompute',
#         'USER':'postgres',
#         'PASSWORD':'dash$123',
#         'HOST':'database-uno.c5gy8c44i5qo.us-east-2.rds.amazonaws.com',
#         'PORT':'5432',
#     }
# }

# # Local db on colva3
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "supabase_local",
#         "USER": "postgres",
#         "PASSWORD": "postgres",
#         # "HOST": "10.1.19.77",
#         "HOST": "colva3.dashlab.in",
#         "PORT": "5432",
#     }
# }

# CockroachDB migration
DATABASES = {
    "default": {
        "ENGINE": "scheduler.db.cockroach",
        "NAME": "peercompute",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "anjuna2.dashlab.in",   # or HAProxy VIP/host
        "PORT": "26257",
        "OPTIONS": {
            "sslmode": "verify-full",
            "sslrootcert": "/var/lib/cockroach/certs/ca.crt",
            "sslcert": "/var/lib/cockroach/certs/client.root.crt",
            "sslkey": "/var/lib/cockroach/certs/client.root.key",
        },
        "CONN_MAX_AGE": 600,
    }
}


# # SUPABASE
# # When USE_SUPABASE_REST=true (e.g. college WiFi), connect via HTTPS (port 443) instead of Postgres port 5432.
# SUPABASE_REST_URL = os.environ.get("SUPABASE_URL", "https://uufnsxmqnwegackubear.supabase.co")
# SUPABASE_ANON_KEY = os.environ.get("SUPABASE_ANON_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Zm5zeG1xbndlZ2Fja3ViZWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0Mzk2NjcsImV4cCI6MjA1NTAxNTY2N30.6HKN271GdBBhmNjfSI9vS2g-wEpJ9r2Uf-_xvUBCEfA")
# USE_SUPABASE_REST = os.environ.get("USE_SUPABASE_REST", "").lower() in ("1", "true", "yes")
#
# if USE_SUPABASE_REST and SUPABASE_ANON_KEY:
#     DATABASES = {
#         "default": {
#             "ENGINE": "scheduler.db.supabase",
#             "NAME": "postgres",
#             "OPTIONS": {
#                 "SUPABASE_REST_URL": SUPABASE_REST_URL,
#                 "SUPABASE_ANON_KEY": SUPABASE_ANON_KEY,
#             },
#             "CONN_MAX_AGE": 0,
#             "CONN_HEALTH_CHECKS": False,
#             "AUTOCOMMIT": True,
#             "TIME_ZONE": None,
#         }
#     }
# else:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": "postgres",
#             "USER": "postgres.uufnsxmqnwegackubear",
#             "PASSWORD": "16G6MNonNa7ny9pG",
#             "HOST": "aws-0-ap-south-1.pooler.supabase.com",
#             "PORT": "5432",
#             "OPTIONS": {
#                 "options": "-c pool_mode=session"
#             },
#         }
#     }
#

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
