# Generated by Django 5.0.3 on 2024-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_cpu_efficiency_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='function_invocations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_provider', True), ('function_invocations__len', 0), _connector='OR'), name='function_invocation_only_if_provider'),
        ),
    ]
