# Generated by Django 5.0.3 on 2024-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_function_invocations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delay',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='time_of_last_startjob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
