# Generated by Django 5.0.3 on 2024-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_user_delay_user_reputation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inflight_jobs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_provider', True), ('delay', {}), _connector='OR'), name='delay_only_if_provider'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_provider', True), ('time_of_last_startjob__isnull', True), _connector='OR'), name='time_of_last_startjob_only_if_provider'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_provider', True), ('inflight_jobs__len', 0), _connector='OR'), name='inflight_jobs_only_if_provider'),
        ),
    ]
