# Generated by Django 5.0.3 on 2024-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_inflight_jobs_user_delay_only_if_provider_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='time_of_last_startjob_only_if_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inflight_jobs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_of_last_startjob',
        ),
        migrations.AlterField(
            model_name='user',
            name='delay',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='function_invocations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
