# Generated by Django 5.0.3 on 2025-01-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_user_time_of_last_startjob_only_if_provider_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='inflight_jobs_only_if_provider',
        ),
    ]
