# Generated by Django 5.0.3 on 2025-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_user_time_of_last_startjob_only_if_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cached_images',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disk_cache_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_provider', True), ('cached_images', {}), _connector='OR'), name='cached_images_only_if_provider'),
        ),
    ]
