# Generated by Django 5.0.3 on 2025-12-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_user_inflight_jobs_only_if_provider'),
        ('profiles', '0008_remove_user_inflight_jobs_only_if_provider_and_more'),
    ]

    operations = [
    ]
