# Generated by Django 5.0.3 on 2025-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_merge_20250410_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disk_cache_limit',
            field=models.IntegerField(default=0),
        ),
    ]
