# Generated by Django 5.0.3 on 2025-05-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_user_disk_cache_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disk_cache_limit',
        ),
    ]
