# Generated by Django 6.0.4 on 2026-07-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_user_cpi_memory_bandwidth_clock_hz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='r_cpu',
            field=models.FloatField(blank=True, help_text='CPU performance ratio vs BEM baseline', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='r_disk',
            field=models.FloatField(blank=True, help_text='Disk throughput ratio vs BEM baseline', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='r_mem',
            field=models.FloatField(blank=True, help_text='Memory bandwidth ratio vs BEM baseline', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='r_net',
            field=models.FloatField(blank=True, help_text='Network throughput ratio vs BEM baseline', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='s_disk_mbps',
            field=models.FloatField(blank=True, help_text='Absolute disk throughput MB/s', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='s_net_mbps',
            field=models.FloatField(blank=True, help_text='Absolute network throughput MB/s', null=True),
        ),
    ]
